# Generated by Django 4.2 on 2023-05-16 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_you_find_us', models.CharField(max_length=30)),
                ('about_our_location', models.CharField(max_length=56)),
                ('About_organization_space', models.CharField(max_length=256)),
                ('waitin_time', models.CharField(max_length=256)),
                ('about_our_employees', models.CharField(max_length=256)),
                ('about_our_service', models.CharField(max_length=256)),
                ('do_you_intend_to_return', models.CharField(max_length=256)),
                ('criticize_or_praise', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
