# Generated by Django 4.2 on 2023-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
