# Generated by Django 4.2 on 2023-05-19 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0002_questionario_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='criticize_or_praise',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='user',
        ),
        migrations.AddField(
            model_name='questionario',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
