# Generated by Django 4.2 on 2023-05-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0005_answers_createat_answers_percentage_answers_results'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionario',
        ),
        migrations.AlterField(
            model_name='answers',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='results',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
