# Generated by Django 4.2 on 2023-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0006_delete_questionario_alter_answers_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
